###############################################################################
# SET PARAMETERS FOR TRAINING
###############################################################################
EXECUTABLE: crawler
STEPS: 200000
VERBOSE_STEPS: 100
CHECKPOINTS: 10000
NO_GRAPHICS: False

BUFFER_SIZE: 10000
BATCH_SIZE: 32

ACTOR_LEARNING_RATE: 0.003
CRITIC_LEARNING_RATE: 0.003

TAU: 0.99
GAMMA: 0.99


LAYER_SIZES:
  - 64
  - 32
  - 16


###############################################################################
# SET PARAMETERS FOR RUN
###############################################################################
RUN_EXECUTABLE: crawler
RUN_MODEL: models/crawler/actor_target_150000.h5
RUN_EPISODES: 1000
VERBOSE_EPISODES: 100
