###############################################################################
# SET PARAMETERS FOR TRAINING
###############################################################################
EXECUTABLE: crawler
STEPS: 30000
VERBOSE_STEPS: 100

BUFFER_SIZE: 10000
BATCH_SIZE: 4096

ACTOR_LEARNING_RATE: 0.01
CRITIC_LEARNING_RATE: 0.01

TAU: 0.99
GAMMA: 0.99


LAYER_SIZES:
  - 1024
  - 512
  - 256
