###############################################################################
# SET PARAMETERS FOR TRAINING
###############################################################################
EXECUTABLE: crawler
STEPS: 5000
VERBOSE_STEPS: 10

BUFFER_SIZE: 50000
BATCH_SIZE: 500

ACTOR_LEARNING_RATE: 0.001
CRITIC_LEARNING_RATE: 0.001

TAU: 0.99
GAMMA: 0.99


LAYER_SIZES:
  - 1024
  - 512
  - 256
