###############################################################################
# SET PARAMETERS FOR TRAINING
###############################################################################
EXECUTABLE: crawler
STEPS: 100
VERBOSE_STEPS: 10

BUFFER_SIZE: 500
BATCH_SIZE: 1024

ACTOR_LEARNING_RATE: 0.001
CRITIC_LEARNING_RATE: 0.001

GAMMA: 0.99

LAYER_SIZES:
  - 1024
  - 512
  - 256
