###############################################################################
# SET PARAMETERS FOR TRAINING
###############################################################################
EXECUTABLE: crawler
STEPS: 2000
VERBOSE_STEPS: 100