###############################################################################
# SET PARAMETERS FOR TRAINING
###############################################################################
EXECUTABLE: crawler
STEPS: 100000
VERBOSE_STEPS: 1000
CHECKPOINTS: 10000
NO_GRAPHICS: False

OUNOISE: TRUE

GAUSSIAN_START: 0.3
GAUSSIAN_DECAY: 0.5

BUFFER_SIZE: 10000
BATCH_SIZE: 32

ACTOR_LEARNING_RATE: 0.001
CRITIC_LEARNING_RATE: 0.001

TAU: 0.99
GAMMA: 0.99


LAYER_SIZES:
  - 32
  - 32
  - 32


###############################################################################
# SET PARAMETERS FOR RUN
###############################################################################
RUN_EXECUTABLE: crawler
RUN_MODEL: models/crawler/actor_target_150000.h5
RUN_EPISODES: 1000
VERBOSE_EPISODES: 100