###############################################################################
# SET PARAMETERS FOR TRAINING
###############################################################################
EXECUTABLE: crawler
STEPS: 2000000
VERBOSE_STEPS: 100
CHECKPOINTS: 10000
NO_GRAPHICS: True

BUFFER_SIZE: 10000
BATCH_SIZE: 512

ACTOR_LEARNING_RATE: 0.001
CRITIC_LEARNING_RATE: 0.001

TAU: 0.99
GAMMA: 0.99


LAYER_SIZES:
  - 128
  - 64
  - 32


###############################################################################
# SET PARAMETERS FOR RUN
###############################################################################
RUN_EXECUTABLE: crawler
RUN_MODEL: models/crawler/actor_target_10000.h5
RUN_EPISODES: 1000
VERBOSE_EPISODES: 5
