###############################################################################
# SET PARAMETERS FOR TRAINING
###############################################################################
EXECUTABLE: crawler
STEPS: 2000
VERBOSE_STEPS: 100

BUFFER_SIZE: 5000
BATCH_SIZE: 1024

ACTOR_LEARNING_RATE: 0.001
CRITIC_LEARNING_RATE: 0.001

LAYER_SIZES:
  - 1024
  - 512
  - 256
