###############################################################################
# SET PARAMETERS FOR TRAINING
###############################################################################
EXECUTABLE: crawler
STEPS: 2000
VERBOSE_STEPS: 100

BUFFER_SIZE: 50000
BATCH_SIZE: 1024
