###############################################################################
# SET PARAMETERS FOR TRAINING
###############################################################################
TRAIN_MODE: True
EXECUTABLE: walker
EPISODES: 100