###############################################################################
# SET PARAMETERS FOR TRAINING
###############################################################################
EXECUTABLE: crawler
STEPS: 2000000
VERBOSE_STEPS: 100

BUFFER_SIZE: 10000
BATCH_SIZE: 1024

ACTOR_LEARNING_RATE: 0.001
CRITIC_LEARNING_RATE: 0.001

TAU: 0.99
GAMMA: 0.99


LAYER_SIZES:
  - 128
  - 128
  - 128
