###############################################################################
# SET PARAMETERS FOR TRAINING
###############################################################################
EXECUTABLE: crawler
STEPS: 100000
VERBOSE_STEPS: 1000
CHECKPOINTS: 20000
NO_GRAPHICS: False

OUNOISE: False

GAUSSIAN_START: 1.0
GAUSSIAN_DECAY: 0.8
GAUSSIAN_MIN: 0.1

BUFFER_SIZE: 50000
BATCH_SIZE: 32

ACTOR_LEARNING_RATE: 0.0001
CRITIC_LEARNING_RATE: 0.0001

TAU: 0.9999
GAMMA: 0.99


LAYER_SIZES:
  - 256
  - 256

###############################################################################
# SET PARAMETERS FOR RUN
###############################################################################
RUN_EXECUTABLE: crawler
RUN_MODEL: models/crawler/actor_target_100000.pt
RUN_STEPS: 10000
RUN_VERBOSE_STEPS: 1000
RUN_NO_GRAPHICS: False
