###############################################################################
# SET GENERAL PARAMETERS
###############################################################################
EXECUTABLE: crawler
STEPS: 1000000
VERBOSE_STEPS: 1000
CHECKPOINTS: 50000
NO_GRAPHICS: False
TIME_SCALE: 50.0

LAYER_SIZES:
  - 256
  - 256
  - 256

###############################################################################
# SET PARAMETERS FOR TRAINING WITH PPO
###############################################################################
PPO_BUFFER_SIZE: 20480
PPO_BATCH_SIZE: 2048
PPO_EPOCHS: 3

PPO_STD: 1.0


PPO_GAMMA: 0.99
PPO_LAMBDA: 0.95
PPO_EPSILON: 0.2
CRITIC_DISCOUNT: 0.5
ENTROPY_BETA: 0.0001

PPO_ACTOR_LEARNING_RATE: 0.001
PPO_CRITIC_LEARNING_RATE: 0.001

###############################################################################
# SET PARAMETERS FOR TRAINING WITH DDPG
###############################################################################
OUNOISE: False

GAUSSIAN_START: 1.0
GAUSSIAN_DECAY: 0.8
GAUSSIAN_MIN: 0.1

BUFFER_SIZE: 50000
BATCH_SIZE: 32

ACTOR_LEARNING_RATE: 0.0001
CRITIC_LEARNING_RATE: 0.0001

TAU: 0.9999
GAMMA: 0.99

###############################################################################
# SET PARAMETERS FOR RUN
###############################################################################
RUN_EXECUTABLE: crawler
RUN_MODEL: models/vm_crawler/actor_3000000.pt
RUN_STEPS: 10000
RUN_VERBOSE_STEPS: 1000
RUN_NO_GRAPHICS: False
