###############################################################################
# SET PARAMETERS FOR TRAINING
###############################################################################
EXECUTABLE: crawler
STEPS: 100000
VERBOSE_STEPS: 1000
CHECKPOINTS: 20000
NO_GRAPHICS: False

OUNOISE: False

GAUSSIAN_START: 0.1
GAUSSIAN_DECAY: 0.5

BUFFER_SIZE: 50000
BATCH_SIZE: 32

ACTOR_LEARNING_RATE: 0.001
CRITIC_LEARNING_RATE: 0.001

TAU: 0.99
GAMMA: 0.99


LAYER_SIZES:
  - 256
  - 256
  - 256


###############################################################################
# SET PARAMETERS FOR RUN
###############################################################################
RUN_EXECUTABLE: crawler
RUN_MODEL: models/crawler/actor_target_150000.h5
RUN_EPISODES: 1000
VERBOSE_EPISODES: 100
